### ISSUE TITLE
Is it possible to generate tailwind.config.js from single tokens.json file

### ISSUE THREAD

**Issue by PeterWorakarn** [nado1001/sd-tailwindcss-transformer#110]
This plugin seem to support only when using with `style-dictionary init basic`
but I want to use with Figma Token plugin which generate only single tokens.js file like this.

<img width="143" alt="Screenshot_44" src="https://user-images.githubusercontent.com/57410426/203498635-5a75a67d-288d-4f57-a7b8-f655f8ae6ef4.png"> 

Any recommendation ?

Thanks.

**Comment by nado1001** [comment]
@PeterWorakarn 
Thanks for your interest in this library!
I would like to know more about the situation. Do you have the actual source code, CodeSandbox, etc.?

**Comment by PeterWorakarn** [comment]
@nado1001  Hi, I create repository for this issues.

[Figma-tokens export](https://github.com/PeterWorakarn/figma-tokens/tree/Tailwind)

**Comment by nado1001** [comment]
@PeterWorakarn 
Hi, Thanks for providing the repository.

When using figma tokens to export design tokens, the first property of the object should come with a [name supported by tailwind](https://tailwindcss.com/docs/theme#configuration-reference) (`colors` for colors).
This is feasible with figma tokens.

Also, export without checking `All token sets` and `Include parent key`.

I have prepared a sample using the tokens.json you provided.
Does this match what you want to do?
https://codesandbox.io/s/style-dictionary-tailwind-figma-tokens-example-j83l6m

**Comment by PeterWorakarn** [comment]
@nado1001 It works ! 
Thank you very much, I will research more about Figma token cause some format is not support in Style Dictionary.
